# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('data', models.DateTimeField(verbose_name='data da visita')),
                ('instrutor', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palestrante', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=20)),
                ('data', models.DateTimeField(verbose_name='data da palestra')),
                ('descricao', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=30)),
                ('data', models.DateTimeField(verbose_name='data da visita')),
                ('descricao', models.CharField(max_length=140)),
            ],
        ),
    ]
