# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minicurso',
            name='imagem',
            field=models.ImageField(default='main/static/main/no_photo.png', upload_to='minicursos'),
        ),
        migrations.AddField(
            model_name='palestra',
            name='imagem',
            field=models.ImageField(default='main/static/main/no_photo.png', upload_to='palestras'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='imagem',
            field=models.ImageField(default='main/static/main/no_photo.png', upload_to='visitas'),
        ),
        migrations.AlterField(
            model_name='minicurso',
            name='descricao',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='descricao',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='descricao',
            field=models.TextField(max_length=140),
        ),
    ]
