# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20170420_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minicurso',
            name='imagem',
            field=models.ImageField(default='no_photo.png', upload_to='minicursos'),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='imagem',
            field=models.ImageField(default='no_photo.png', upload_to='palestras'),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='imagem',
            field=models.ImageField(default='/home/data/Work/Inbox/SEE/see_website_paw/media/no_photo.png', upload_to='visitas'),
        ),
    ]
