# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20170421_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitatecnica',
            name='imagem',
            field=models.ImageField(default='media/no_photo.png', upload_to='visitas'),
        ),
    ]
