# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('see_profile', '0001_initial'),
        ('eventos', '0004_auto_20170421_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minicurso',
            options={'ordering': ('data',)},
        ),
        migrations.AlterModelOptions(
            name='palestra',
            options={'ordering': ('data',)},
        ),
        migrations.AlterModelOptions(
            name='visitatecnica',
            options={'ordering': ('data',)},
        ),
        migrations.AddField(
            model_name='minicurso',
            name='inscritos',
            field=models.ManyToManyField(to='see_profile.User'),
        ),
        migrations.AddField(
            model_name='palestra',
            name='interesse',
            field=models.ManyToManyField(to='see_profile.User'),
        ),
        migrations.AddField(
            model_name='visitatecnica',
            name='inscritos',
            field=models.ManyToManyField(to='see_profile.User'),
        ),
        migrations.AlterField(
            model_name='minicurso',
            name='data',
            field=models.DateTimeField(verbose_name='data do minicurso'),
        ),
        migrations.AlterField(
            model_name='minicurso',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='minicurso',
            name='instrutor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='minicurso',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='palestrante',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='visitatecnica',
            name='local',
            field=models.CharField(max_length=50),
        ),
    ]
