# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('see_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ProfileUser',
        ),
    ]
